add example demo

diff --git a/examples/stargaze_demo/scripts/two-chainz b/examples/stargaze_demo/scripts/two-chainz
--- a/examples/stargaze_demo/scripts/two-chainz
+++ b/examples/stargaze_demo/scripts/two-chainz
@@ -1,20 +1,20 @@
 #!/bin/bash
-# two-chainz creates two iris chains and configures the relayer to 
+# two-chainz creates two gaiad chains and configures the relayer to
 
 SCRIPTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
-GAIA_DATA="$(pwd)/data"
+SPECY_DATA="$(pwd)/data"
 RELAYER_DIR="$(dirname $SCRIPTDIR)"
 RELAYER_CONF="$HOME/.relayer"
 
-# Ensure iris is installed
-if ! [ -x "$(which iris)" ]; then
-  echo "Error: iris is not installed. Try running 'make build-gaia'" >&2
+# Ensure specyd is installed
+if ! [ -x "$(which specyd)" ]; then
+  echo "Error: specyd is not installed. Try running 'make build-specy'" >&2
   exit 1
 fi
 
 # Display software version for testers
-echo "GAIA VERSION INFO:"
-iris version --long
+echo "SPECYD VERSION INFO:"
+specyd version --long
 
 # Ensure jq is installed
 if [[ ! -x "$(which jq)" ]]; then
@@ -24,7 +24,7 @@ if [[ ! -x "$(which jq)" ]]; then
 fi
 
 # Ensure user understands what will be deleted
-if [[ -d $GAIA_DATA ]] && [[ ! "$1" == "skip" ]]; then
+if [[ -d $SPECY_DATA ]] && [[ ! "$1" == "skip" ]]; then
   read -p "$(basename $0) will delete \$(pwd)/data and \$HOME/.relayer folders. Do you wish to continue? (y/n): " -n 1 -r
   echo
   if [[ ! $REPLY =~ ^[Yy]$ ]]; then
@@ -33,24 +33,24 @@ if [[ -d $GAIA_DATA ]] && [[ ! "$1" == "skip" ]]; then
 fi
 
 # Delete data from old runs
-rm -rf $GAIA_DATA &> /dev/null
+rm -rf $SPECY_DATA &> /dev/null
 rm -rf $RELAYER_CONF &> /dev/null
 
-# Stop existing iris processes
-killall iris &> /dev/null
+# Stop existing gaiad processes
+killall specyd &> /dev/null
 
 set -e
 
 chainid0=ibc-2
 chainid1=ibc-1
 
-echo "Generating gaia configurations..."
-mkdir -p $GAIA_DATA && cd $GAIA_DATA && cd ../
-./scripts/one-chain iris $chainid0 ./data 26657 26656 6060 9090 iris uiris 8545 8546
-./scripts/one-chain iris $chainid1 ./data 26557 26556 6061 9091 iris uiris 8535 8536
+echo "Generating specy configurations..."
+mkdir -p $SPECY_DATA && cd $SPECY_DATA && cd ../
+./scripts/one-chain specyd $chainid0 ./data 26657 26656 6060 9090 stake samoleans
+./scripts/one-chain specyd $chainid1 ./data 26557 26556 6061 9091 stake samoleans
 
-[ -f $GAIA_DATA/$chainid0.log ] && echo "$chainid0 initialized. Watch file $GAIA_DATA/$chainid0.log to see its execution."
-[ -f $GAIA_DATA/$chainid1.log ] && echo "$chainid1 initialized. Watch file $GAIA_DATA/$chainid1.log to see its execution."
+[ -f $SPECY_DATA/$chainid0.log ] && echo "$chainid0 initialized. Watch file $SPECY_DATA/$chainid0.log to see its execution."
+[ -f $SPECY_DATA/$chainid1.log ] && echo "$chainid1 initialized. Watch file $SPECY_DATA/$chainid1.log to see its execution."
 
 cd $RELAYER_DIR
 
@@ -63,8 +63,8 @@ echo "Generating rly configurations..."
 rly config init
 rly chains add-dir configs/chains
 
-SEED0=$(jq -r '.mnemonic' $GAIA_DATA/ibc-2/key_seed.json)
-SEED1=$(jq -r '.mnemonic' $GAIA_DATA/ibc-1/key_seed.json)
+SEED0=$(jq -r '.mnemonic' $SPECY_DATA/ibc-2/key_seed.json)
+SEED1=$(jq -r '.mnemonic' $SPECY_DATA/ibc-1/key_seed.json)
 echo "Key $(rly keys restore ibc-2 testkey "$SEED0") imported from ibc-2 to relayer..."
 echo "Key $(rly keys restore ibc-1 testkey "$SEED1") imported from ibc-1 to relayer..."
 
